package com.hazel.android.data

import android.content.Context
import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File

/**
 * One saved cookie set, covering a single site.
 *
 * [content] is Netscape cookie file text, which is the format yt-dlp reads. An entry can be
 * switched off without deleting it, in which case it is left out of the file handed to
 * yt-dlp but stays in the list.
 */
data class CookieEntry(
    val id: Long,
    val url: String,
    val title: String,
    val content: String,
    val enabled: Boolean = true
) {
    /** First few lines of the cookie text, for the row summary. */
    fun preview(lines: Int = 3): String =
        content.lineSequence().take(lines).joinToString("\n").take(300)
}

/**
 * Stores the user's cookie sets and keeps the file yt-dlp reads in step with them.
 *
 * Cookies let yt-dlp reach content the site will only serve to a signed-in viewer:
 * age-restricted videos, members-only posts, and anything behind a login wall. They are
 * kept in the app's private storage and are never sent anywhere except to yt-dlp.
 *
 * The list is held as JSON in the same preference store as the rest of the settings, which
 * avoids adding a database for what is normally a handful of entries.
 */
object CookieRepository {

    private val USE_COOKIES_KEY = booleanPreferencesKey("use_cookies")
    private val COOKIES_KEY = stringPreferencesKey("cookie_entries")

    /** Header yt-dlp expects at the top of a Netscape cookie file. */
    const val FILE_HEADER = "# Netscape HTTP Cookie File\n" +
            "# Generated by Hazel\n" +
            "# This is a generated file. Do not edit."

    // ── Master switch ──

    fun getUseCookies(context: Context): Flow<Boolean> =
        context.dataStore.data.map { prefs -> prefs[USE_COOKIES_KEY] ?: false }

    suspend fun setUseCookies(context: Context, enabled: Boolean) {
        context.dataStore.edit { prefs -> prefs[USE_COOKIES_KEY] = enabled }
        writeCookieFile(context)
    }

    // ── Entries ──

    fun getEntries(context: Context): Flow<List<CookieEntry>> =
        context.dataStore.data.map { prefs -> decode(prefs[COOKIES_KEY]) }

    /**
     * Adds an entry, or replaces the one that already covers the same site and title.
     * Signing in again to refresh an expired set therefore updates in place rather than
     * leaving two entries behind.
     */
    suspend fun upsert(context: Context, entry: CookieEntry) {
        context.dataStore.edit { prefs ->
            val existing = decode(prefs[COOKIES_KEY])
            val match = existing.indexOfFirst {
                it.id == entry.id || (it.url == entry.url && it.title == entry.title)
            }
            val updated = if (match >= 0) {
                existing.toMutableList().apply { this[match] = entry.copy(id = existing[match].id) }
            } else {
                existing + entry
            }
            prefs[COOKIES_KEY] = encode(updated)
        }
        writeCookieFile(context)
    }

    suspend fun setEnabled(context: Context, id: Long, enabled: Boolean) {
        context.dataStore.edit { prefs ->
            val updated = decode(prefs[COOKIES_KEY]).map {
                if (it.id == id) it.copy(enabled = enabled) else it
            }
            prefs[COOKIES_KEY] = encode(updated)
        }
        writeCookieFile(context)
    }

    suspend fun delete(context: Context, id: Long) {
        context.dataStore.edit { prefs ->
            prefs[COOKIES_KEY] = encode(decode(prefs[COOKIES_KEY]).filter { it.id != id })
        }
        writeCookieFile(context)
    }

    suspend fun deleteAll(context: Context) {
        context.dataStore.edit { prefs -> prefs[COOKIES_KEY] = encode(emptyList()) }
        writeCookieFile(context)
    }

    // ── The file yt-dlp reads ──

    /** Private to the app; cookies never reach public storage. */
    fun cookieFile(context: Context): File = File(context.cacheDir, "cookies.txt")

    /**
     * Rewrites the cookie file from the entries that are currently switched on.
     *
     * Called after every change so the file can never describe a state the list does not.
     * When cookies are off, or nothing is enabled, the file is emptied rather than deleted,
     * which keeps a stale set from being picked up later.
     */
    suspend fun writeCookieFile(context: Context) = withContext(Dispatchers.IO) {
        val enabled = if (getUseCookies(context).first()) {
            getEntries(context).first().filter { it.enabled && it.content.isNotBlank() }
        } else {
            emptyList()
        }

        val file = cookieFile(context)
        if (enabled.isEmpty()) {
            runCatching { file.writeText("") }
            return@withContext
        }

        val text = buildString {
            append(FILE_HEADER)
            append('\n')
            enabled.forEach { entry ->
                entry.content.lineSequence().forEach { line ->
                    // Per-entry headers and comments are dropped: one header for the file.
                    if (line.isNotBlank() && !line.startsWith("#")) {
                        append(line)
                        append('\n')
                    }
                }
            }
        }
        runCatching { file.writeText(text) }
    }

    /**
     * The cookie file to hand yt-dlp, or null when cookies are off or none are stored.
     * The file is rewritten first so a change made while a fetch was queued still applies.
     */
    suspend fun activeCookieFile(context: Context): File? {
        if (!getUseCookies(context).first()) return null
        writeCookieFile(context)
        val file = cookieFile(context)
        return file.takeIf { it.exists() && it.length() > 0 }
    }

    /** Whole cookie file as text, for copying out. */
    suspend fun exportText(context: Context): String = withContext(Dispatchers.IO) {
        writeCookieFile(context)
        runCatching { cookieFile(context).readText() }.getOrDefault("")
    }

    /**
     * Takes cookie text the user copied from elsewhere and stores it as a new entry.
     * Anything that is not a Netscape cookie file is rejected rather than saved as junk.
     */
    suspend fun importText(context: Context, text: String, title: String): Boolean {
        val body = text.lineSequence()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .joinToString("\n")
        if (body.isBlank()) return false

        upsert(
            context,
            CookieEntry(
                id = System.currentTimeMillis(),
                url = "",
                title = title,
                content = body,
                enabled = true
            )
        )
        return true
    }

    // ── JSON ──

    private fun encode(entries: List<CookieEntry>): String {
        val array = JSONArray()
        entries.forEach { entry ->
            array.put(
                JSONObject().apply {
                    put("id", entry.id)
                    put("url", entry.url)
                    put("title", entry.title)
                    put("content", entry.content)
                    put("enabled", entry.enabled)
                }
            )
        }
        return array.toString()
    }

    private fun decode(raw: String?): List<CookieEntry> {
        if (raw.isNullOrBlank()) return emptyList()
        return runCatching {
            val array = JSONArray(raw)
            (0 until array.length()).mapNotNull { index ->
                array.optJSONObject(index)?.let { json ->
                    CookieEntry(
                        id = json.optLong("id"),
                        url = json.optString("url"),
                        title = json.optString("title"),
                        content = json.optString("content"),
                        enabled = json.optBoolean("enabled", true)
                    )
                }
            }
        }.getOrDefault(emptyList())
    }
}
